version: '3'
services:

  # mysql-db:
  #   image: mysql:5.7
  #   ports:
  #     - 3306:3306
  #   environment: 
  #     - MYSQL_ROOT_PASSWORD=parola

  mongo-db:
    image: mongo
    ports:
      - 27017:27017

  mongo-interface:
    image: mongo-express
    ports:
      - 8081:8081
#  server:
#    build: .
#    ports:
#      - 3000:3000
